### ISSUE TITLE
Error scroll the body below modal

### ISSUE THREAD

**Issue by gustavowiller** [tanmuhittin/nova-scroll-top#1]
Version: 0.3

What is expected?
- The body page don't scroll when occurs error on modal.

What is actually happening?
- The body page scrolling when occurs error on modal, generated by Nova Action.

**Comment by tanmuhittin** [comment]
Please verify that fix works using dev-master 👍

**Comment by gustavowiller** [comment]
It works! Thanks bro

**Comment by tanmuhittin** [comment]
https://github.com/tanmuhittin/nova-scroll-top/releases/tag/0.4
